config/routes.rb
Rails.application.routes.draw do
    
    mount Ckeditor::Engine => '/ckeditor'

    #Set up devise routes for Users
    devise_for :users

    #If user is signed in set specific homepage
    authenticated :user do
		root to: "users#home", :as => "authenticated-root"
	end

    #standard root
	root to: "home#home"

    #index of all the blogs, used for development
    get 'blogs/index_all', to: 'blogs#index_all'


    get 'users/discover', to: 'users#discover'
    get "users/home", to: "users#home"


    resources :users do
        member do
            get :following
        end
    end

    resources :posts do
        resources :comments
    end

    get "search", to: "search#search"


    resources :relationships, only: [:create, :destroy]

    resources :blogs do
        member do
            get :followers
        end
    end
    

end

app/models/blog.rb
require 'elasticsearch/model'

class Blog < ActiveRecord::Base
	
	include Elasticsearch::Model
	include Elasticsearch::Model::Callbacks

	validates :title, presence: true
	
	has_many :posts

	belongs_to :user

	has_many :passive_relationships, class_name:  "Relationship",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy

  	has_many :followers, through: :passive_relationships, source: :follower

end
 
# Index all article records from the DB to Elasticsearch
Blog.import

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	def new
	  @blog = Blog.new
	end


	def show
	  @blog = Blog.find(params[:id])
	end


	def create
	  @blog = Blog.create(blog_params)
	  @blog.user = current_user
	  @blog.username = current_user.username
	  if @blog.save
	  	  redirect_to blog_path(@blog.id)
	  else
	  	  redirect_to root_path
	  end
	end


	def edit
		@blog = Blog.find(params[:id])
	end

	def destroy
		@blog = Blog.find(params[:id])
		@posts = @blog.posts
		
		@posts.each do |i|
			i.destroy
		end
		
		if @blog.destroy
			redirect_to blogs_path
		else
			redirect :back
		end
	end

	def update
		@blog = Blog.find(params[:id])
		@blog.description = params[:blog][:description]
		@blog.title = params[:blog][:title]
		@blog.location = params[:blog][:location]
		if @blog.save 
			redirect_to blog_path(@blog.id)
		else
			redirect_to :back
		end
	end


	def index
	  @blogs = User.find(current_user).blogs
	  @following = current_user.following.order('created_at DESC')
	end

	def index_all
	  @blogs = Blog.all
	end

	private

	def blog_params
		params.require(:blog).permit(:title, :description)
	end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog2.html.erb
<div class="container-fluid">
	<div class="row">
		<div class = "col-xs-12 ">
			<div class ="col-xs-2" id="in-post-sidebar">
			<% user = User.find(blog.user_id) %>

			<% if user_signed_in? and user == current_user %>
				<h4> <%= link_to user.username, root_path, class: "header-link" %> </h4>
				<%= link_to image_tag(user.avatar.url(:thumb), :class => "img-circle avatar img-discover center"), root_path %>
			<% else %>
				<h4> <%= link_to user.username, user_path(user), class: "header-link" %> </h4>
				<%= link_to image_tag(user.avatar.url(:thumb), :class => "img-circle avatar img-discover center"), user_path(user) %>
			<% end %>

			</div>
			<div class="col-xs-10 blog-result-body border-bottom">
				<div>
					<span> <h4 class="my-header" style="float:left"> <%= link_to blog.title, {controller: "blogs", action: "show", id: blog.id}, :class => "search-link" %> <small> <%= blog.location %> </small> </h4>
					 <h5 style="float:right" id="fix-this"> <small> created <%= Date.parse(blog.created_at).strftime("%b %d") %> </small> </h5> </span>
				</div>
				<div class="col-xs-12 ">
					<%= blog.description.html_safe %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/blogs/_follow_form.html.erb
<%= form_for(current_user.active_relationships.build, remote:true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @blog.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary call-to-action-btn" %>
<% end %>

app/views/blogs/_mini_show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12 blog-border" id="sneak-blog-show">
			<h3 class="my-header"> <%= link_to blog.title, blog_path(blog), class: "header-link" %> <small> <%= blog.location %> </small> </h3>
			<% if blog.posts.last != nil %>
			<div class="container-fluid" id="sneak-post">
					<div>
						<h4 id="sneak-post-title"> <%= blog.posts.last.title%> <span style="float: right"><small>Most recent post was <%=blog.posts.last.created_at.strftime("%b %d") %></small> </span> </h4>
					</div>
					<p> <%= blog.posts.last.content.html_safe %> </p>
					<div class="fadeout"></div>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/blogs/_show_all.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-7 col-xs-offset-2">
			<h3> <%= link_to blog.title, blog_path(id: blog) %> <small> <%= blog.location %> </small> </h3>
		</div>
		<div class="col-xs-3">
			<h3> <small><%=blog.user.username%> </small></h3>
		</div>
	</div>
</div>

app/views/blogs/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @blog.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-primary danger-btn-custom" %>
<% end %>

app/views/blogs/_user_show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12 blog-border">
			<h4 class="my-header"> <%= link_to blog.title, blog_path(blog), class: "header-link" %> <small> <%= blog.location %> </small> <span style="float:right"> <h5> <small> created <%= blog.created_at.strftime("%b %d") %></small></h5></span> </h4>
			<% if blog.posts.last != nil %>
				<div class= "grey-font">
					<p> <span style="float:left"> <%= blog.followers.count %> followers </span><p>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/blogs/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-2" id="sidebar">
      <h2> Edit Blog </h2>
      <%= link_to blog_path(@blog.id), :class => "btn btn-default", :id => "post-back" do %>
        <span class="glyphicon glyphicon-chevron-left"></span> Back     
      <% end %>
    </div>
    <div class="col-xs-7 col-xs-offset-3">
      <%= simple_form_for @blog, html: {class: "form-horizontal"} do |f| %>
        <div class="form-group">
          <%= f.label :title, class: 'control-label' %>
            <%= f.text_field :title, class: 'form-control'%>
          </div>
        <div class="form-group">
          <%= f.label :description, class: 'control-label'%>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
        <div class="form-group">
          <%= f.label :location, class: 'control-label'%>
            <%= f.text_field :location, class: 'form-control'%>
          </div>
        <div class="form-group">
            <%= f.submit "Confirm", :class => "btn btn-primary call-to-action-btn" %>
          </div>
        <% end %>
        </div>
    </div>
    </div>
</div>

app/views/blogs/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-2" id="sidebar">
			<h1> Home </h1>
			<%= link_to image_tag(current_user.avatar.url(:medium), :class => "img-circle avatar"), root_path, class: "header-link" %>
			<p class="center" style="text-align: center"> <%= current_user.username %> </p>
			<%= link_to "Make a Blog", new_blog_path, :class => "btn btn-primary", :method => :get %>
			<br><br>
			 <h4 class="center" style="text-align: center"> Following </h4> 
			<div class="sidebar-followers">
				<% @following.each do |blog| %>
					<%= render "users/following", :blog => blog  %>
				<% end %>
			</div>
		</div>
		<div class= "col-xs-10 col-xs-offset-2">
			<h1 class="my-header center" > Your Blogs </h1>
			<% @blogs.reverse_each do |blog| %>
			   <%= render "blogs/mini_show", :blog => blog %>
			<%end%>
		</div>
		<div class = "top-right-link">
		<%= link_to root_path, :class => "btn btn-default transparent" do %>
			<span class="glyphicon glyphicon-chevron-left"></span> Home 	
		<% end %>
		</div>
</div>
</div>

app/views/blogs/index_all.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-6 col-xs-offset-4">
		<h2> All Current Blogs </h2>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-9 center">
			<% @blogs.each do |blog| %>
				<%= render "blogs/show_all", :blog => blog %>
			<%end%>
		</div>
	</div>
</div>

app/views/blogs/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 edit-profile">
 
<h2 id="newblog-header"> New Blog </h2>

<%= simple_form_for @blog, url: {action: "create"} do |f| %>
	<div class="form-group">
    <%= f.label :title, class: 'control-label' %> 
    <%= f.text_field :title, autofocus: true, class: "form-control"%> 
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'control-label' %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Create Blog", :class => "btn btn-primary" %>
    </div>
<%end%>
      </div>
    </div>

</div>

app/views/blogs/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div id="sidebar" class="col-xs-2">
			<h2 class="my-header"> <%= @blog.title %> </h2>
			<% if @blog.description != nil %>
			<p class="description"><%= @blog.description.html_safe %></p>
			<% end %>
			<div class="center">
				<% if @blog.user == current_user %>
					<%= link_to image_tag(@blog.user.avatar.url(:medium), :class => "img-circle avatar"), root_path %>
					<p class="center" style="text-align: center"> <%= @blog.user.username %> </p>
				<% else %>
					<%= link_to image_tag(@blog.user.avatar.url(:medium), :class => "img-circle avatar"), user_path(@blog.user) %>
					<p class="center" style="text-align: center"> <%= @blog.user.username %> </p>
				<% end %>
			</div>
			<% if current_user == @blog.user %>
				<%= link_to "New Post", new_post_path(:blogID => @blog), :class => "btn btn-primary", :method => :get %>
				<%= link_to "Edit Blog", edit_blog_path(@blog), :class => "btn btn-primary", :method => :get %>
				<%= link_to "Delete Blog", blog_path(@blog), :class => "btn btn-primary", :id => "danger", method: :delete, data:{confirm: "Are you sure you want to delete this blog?"}%>
			<% else %>
				<% if user_signed_in? %>
					<% if current_user.following?(@blog) %>
						<div id="follow_form"><%= render "blogs/unfollow" %></div>
					<% else %>
						<div id="follow_form"><%= render "blogs/follow_form"  %></div>
					<% end %>
				<% else %>
					<%= link_to "Follow", new_user_session_path, class: "btn btn-primary call-to-action-btn" %>
					<br>
				<% end %>
			<% end %>
			<br>
			<br>
			<p id="followers"> <%= @blog.followers.count %> followers </p>

		</div>
		<div class="col-xs-10 col-xs-offset-2">
		  <% if @blog.posts.last != nil %>
			<% @blog.posts.reverse_each do |post| %>
				<%= render "posts/post", :post => post %>
			<% end %>
		  <% else %>
		  	<h1 style="text-align: center"><small> Post something... </small></h1>
		  <% end %>	
		</div>
</div>