config/routes.rb
Rails.application.routes.draw do
    
    mount Ckeditor::Engine => '/ckeditor'

    #Set up devise routes for Users
    devise_for :users

    #If user is signed in set specific homepage
    authenticated :user do
		root to: "users#home", :as => "authenticated-root"
	end

    #standard root
	root to: "home#home"

    #index of all the blogs, used for development
    get 'blogs/index_all', to: 'blogs#index_all'


    get 'users/discover', to: 'users#discover'
    get "users/home", to: "users#home"


    resources :users do
        member do
            get :following
        end
    end

    resources :posts do
        resources :comments
    end

    get "search", to: "search#search"


    resources :relationships, only: [:create, :destroy]

    resources :blogs do
        member do
            get :followers
        end
    end
    

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, uniqueness: true

  has_many :blogs, dependent: :destroy
  has_many :posts, through: :blogs
  has_many :comments, through: :posts

  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed


  # Follows a blog.
  def follow(chosen_blog)
    active_relationships.create(followed_id: chosen_blog.id)
  end

  # Unfollows a blog.
  def unfollow(chosen_blog)
    active_relationships.find_by(followed_id: chosen_blog.id).destroy
  end

  # Returns true if the current user is following the blog.
  def following?(chosen_blog)
    following.include?(chosen_blog)
  end

  def feed
    Post.where("blog_id IN (?)", following_ids).order('created_at DESC')
  end

  has_attached_file :avatar, 
   :path => ":rails_root/public/system/:class/:attachment/:id_partition/:style/:filename", 
   :url => "/system/:class/:attachment/:id_partition/:style/:filename",
   :styles => { :medium => "300x300>", :thumb => "100x100>"},
   :default_url => "/:attachment/:style/missing.png"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  attr_accessor :login

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_hash).first
    end
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
		@activity = @user.posts.order('created_at DESC').limit(5)
		@blogs = @user.blogs
		@following = @user.following.order('created_at DESC')
	end

	def discover
		@discover_posts = Post.paginate(page: params[:page], per_page: 6).order('created_at DESC')
		respond_to do |format|
			format.html
			format.js
		end
	end

	def home
		@user = current_user
		@following = @user.following.order('created_at DESC')		
		@feed_items = current_user.feed.paginate(page: params[:page], per_page: 5)
	end





end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_following.html.erb
<div class="container-fluid">
	<div class = "row" >
		<div class = "col-md-12">
			<%= link_to image_tag(blog.user.avatar.url(:thumb), :class => "img-circle img-discover"), user_path(blog.user.id) %>
		</div>
		<div class = "col-md-12">
			<h5> <%= link_to blog.title, blog_path(blog.id), class: "post-header my-header" %> </h5>
			<p> <%= blog.description %> </p>
		</div>
	</div>
</div>

app/views/users/_paginate_test.html.erb
<div id="discover-post">
	<% discover_posts.each do |post| %>
		<%= render "posts/post3", :post => post %>
	<% end %>
</div>
<div id="infinite-scrolling">
	<%= will_paginate discover_posts %>
</div>

app/views/users/discover.html.erb
<div class="container-fluid">
	<div class="row">
		<div class= "col-xs-10 col-xs-offset-1">
			<h1 style="text-align:center" id="discover-header"> Discover </h1>
			<p class="subtext center"> View other posts and see what the world is up to </p>
			<div id="discover-post">
				<% @discover_posts.each do |post| %>
					<%= render "posts/post3", :post => post %>
				<% end %>
			</div>
			<div id="infinite-scrolling">
				<%= will_paginate @discover_posts %>
			</div>
		</div>
	</div>
</div>

app/views/users/discover.js.erb
$('#discover-post').append('<% j @discover_posts.each do |post| %>',
								'<%= j render "posts/post3", :post => post %>',
					   		'<% j end %>');
<% if @discover_posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @discover_posts %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/users/home.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-2" id="sidebar">
			<h1> Home </h1>
			<%= link_to (image_tag current_user.avatar.url(:medium), :class => "img-circle avatar"), user_path(current_user) %>
			<p><%= current_user.username %> </p>
			<%= link_to "Make a Blog", new_blog_path, :class => "btn btn-primary", :method => :get %>

			<br>
			<br>
			 <h4 class="center" style="text-align: center"> Following </h4> 
			<div class="sidebar-followers">
				<% @following.each do |blog| %>
					<%= render "users/following", :blog => blog  %>
				<% end %>
			</div>
		</div>
		<div class = "row" >
			<div class = "col-xs-10 col-xs-offset-2">
				<div class = "my-header center">
					<h1 class="my-header"> Recent Activity </h1>
				</div>
				<div class= "blog-stream">
					<% @feed_items.each do |post| %>
						<%= render "posts/feed_posts", :post => post %>
					<% end %>
					<div style="padding-left:15px"> <%= will_paginate @feed_items %> </div>
				</div>
			</div>
			<div class = "top-right-link">
				<%= link_to blogs_path(current_user), :class => "btn btn-default transparent" do %>
					Your Blogs <span class="glyphicon glyphicon-chevron-right"></span>			
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-2" id="sidebar">
			<h1> <%= @user.username %> </h1>
			<% if user_signed_in? %>
				<% if @user == current_user %>
					<%= link_to (image_tag @user.avatar.url(:medium), :class => "img-circle avatar"), root_path %>
				<% else %>
					<%= link_to (image_tag @user.avatar.url(:medium), :class => "img-circle avatar"), user_path(@user) %>
				<% end %>
			<% end %>
			 <h4 class="center" style="text-align: center"> Following </h4> 
			<div class="sidebar-followers">
				<% @following.each do |blog| %>
					<%= render "users/following", :blog => blog  %>
				<% end %>
			</div>

		</div>
		<div class = "col-xs-10 col-xs-offset-2">
			<div class = "row">
				<div class= "col-md-8">
					<div class = "my-header center">
					<h3 class="center"> <small> <%=@user.username%>'s &nbsp; </small> Recent Posts </h3>
					</div>
					<div class="activity-stream">
						<% @activity.each do |post| %>
							<%= render "posts/post_activity", :post => post %>
						<% end %>
					</div>
				</div>
				<div class= "col-md-4">
					<div class = "my-header center">
						<h3> Blogs </h3>
					</div>
					<div class= "blog-stream left-border">
					<% @blogs.reverse_each do |blog| %>
						<%= render "blogs/user_show", :blog => blog %>
					<% end %>
					</div>
					
				</div>
			</div>
		</div>
	</div>
</div>