config/routes.rb
Rails.application.routes.draw do
    
    mount Ckeditor::Engine => '/ckeditor'

    #Set up devise routes for Users
    devise_for :users

    #If user is signed in set specific homepage
    authenticated :user do
		root to: "users#home", :as => "authenticated-root"
	end

    #standard root
	root to: "home#home"

    #index of all the blogs, used for development
    get 'blogs/index_all', to: 'blogs#index_all'


    get 'users/discover', to: 'users#discover'
    get "users/home", to: "users#home"


    resources :users do
        member do
            get :following
        end
    end

    resources :posts do
        resources :comments
    end

    get "search", to: "search#search"


    resources :relationships, only: [:create, :destroy]

    resources :blogs do
        member do
            get :followers
        end
    end
    

end

app/models/post.rb
require 'elasticsearch/model'

class Post < ActiveRecord::Base


	validates :location, presence: true
	belongs_to :user
	belongs_to :blog
	has_many :comments


	include Elasticsearch::Model
	include Elasticsearch::Model::Callbacks

	def next
		blog.posts.where("id > ?", self.id).order("id ASC").first
	end

	def previous
		blog.posts.where("id < ?", self.id).order("id DESC").first
	end

end

# Delete the previous articles index in Elasticsearch
Post.__elasticsearch__.client.indices.delete index: Post.index_name rescue nil
 
# Create the new index with the new mapping
Post.__elasticsearch__.client.indices.create \
  index: Post.index_name,
  body: { settings: Post.settings.to_hash, mappings: Post.mappings.to_hash }
 
# Index all article records from the DB to Elasticsearch
Post.import

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	layout :resolve_layout

	def new
		@post = Post.new
		@post.blog_id = params[:blogID]
	end

	def show
		@post = Post.find(params[:id])
		@comments = @post.comments.all
		@comment = @post.comments.build
		@previous_post = @post.previous
		@next_post = @post.next
		@blog = Blog.find(@post.blog_id)
	end

	def create
		@post = Post.create(post_params)
		@post.user = current_user
		@post.username = current_user.username
		if @post.save
			redirect_to blog_path(@post.blog)
		else
			redirect_to root_path
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@comment = @post.comments

		@comment.each do |i| 
			i.destroy
		end
		
		blog = @post.blog_id
		if @post.destroy
			respond_to do |format|
  				format.js {render inline: "location.reload();" }
			end
		end
	end

	def update
		@post = Post.find(params[:id])
		@post.title = params[:post][:title]
		@post.content = params[:post][:content]
		@post.location = params[:post][:location]
		if @post.save 
			redirect_to blog_path(@post.blog_id)
		else
			redirect_to :back
		end
	end

	def edit
		@post = Post.find(params[:id])
	end


	private

	def post_params
		params.require(:post).permit(:title, :content, :location, :blog_id)
	end

	def resolve_layout
		case action_name
		when "show"
			"home_layout"
		else
			"application"
		end
	end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_feed_posts.html.erb
<div class="container-fluid">
	<div class="row">
			<div class ="col-xs-2" id="in-post-sidebar">
			<% user = User.find(post.user_id) %>
			<% if user == current_user %>
				<h4> <%= link_to user.username, root_path, class: "header-link" %> </h4>
				<%= link_to image_tag(user.avatar.url(:thumb), :class => "img-circle avatar img-discover center"), root_path %>
			<% else %>
				<h4> <%= link_to user.username, user_path(user), class: "header-link" %> </h4>
				<%= link_to image_tag(user.avatar.url(:thumb), :class => "img-circle avatar img-discover center"), user_path(user) %>
			<% end %>
			</div>
			<div class="col-xs-10">
				<div class = "recent-activity-size">
					<span> <h4 class="my-header" style="float:left"> <%= link_to post.title, {controller: "posts", action: "show", id: post.id}, :class => "header-link" %> <small> <%= post.location %> </small> </h4>
					 <h5 style="float:right" id="fix-this"> <small> posted <%= time_ago_in_words(post.created_at) %> ago </small> </h5> </span>
				</div>
				<div class="col-xs-12 post-result-body">
					<%= post.content.html_safe %>
					<div class="fadeout"></div>
				</div>
			</div>
	</div>
</div>

app/views/posts/_post.html.erb
<div class="container-fluid post">
	<div class="row">
		<div class="col-xs-12" id="show-post">
			<h3 class="my-header"> <%= link_to post.title, post_path(post), class: "post-header" %> <small> <%= post.location %> </small> <span style="float: right"><small><%=post.created_at.strftime("%d %b %Y") %></small></span></h3>
			<div class="post-content-limiter">
			<p> <%= link_to post.content.html_safe, post_path(post), class: "post-content"%> </p>
			<div class="fadeout"></div>
			</div>

		</div>
		<div class="container-fluid" >
			<% if post.blog.user == current_user %>
			
				<span style="float:right"> 
					<%= link_to post_path(post), method: :delete, remote: true, class: "btn btn-danger btn-sm", id: "post-delete", data:{confirm: "Are you sure you want to delete this post?"} do %>
  						<span class="glyphicon glyphicon-trash"></span>
					<% end %>

					<%= link_to edit_post_path(post), method: :get do %>
						<span class="glyphicon glyphicon-pencil"></span>
					<% end %>
				</span>
			<% end %>
				<div id="comment-count"><span style="float:left"> <%= link_to post_path(post), class: "search-link" do%> <span> <%=post.comments.count %> comments </span> <%end%> </span></div>
		</div>
	</div>
</div>

app/views/posts/_post2.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12">
			<div>
				<span style="float:left"> <h4> <%= link_to post.title, {controller: "posts", action: "show", id: post.id}, :class => "search-link" %> <small> <%= post.location %> </small> </h4> </span>
				<span style="float:right"> <h5> <small> created by </small> <%= User.find(post.user_id).username %> <small> on <%= Date.parse(post.created_at).strftime("%b %d") %> </small> </h5> </span>
			</div>
			<div class="col-xs-12 post-result-body">
				<%= post.content.html_safe %>
				<div class="fadeout"></div>
			</div>
		</div>
	</div>
</div>

app/views/posts/_post3.html.erb
<div class="container-fluid">
	<div class="row">
			<div class ="col-xs-2" id="in-post-sidebar">
			<% user = User.find(post.user_id) %>
			<% if user == current_user %>
				<h4> <%= link_to user.username, root_path, class: "header-link" %> </h4>
				<%= link_to image_tag(user.avatar.url(:thumb), :class => "img-circle avatar img-discover center"), root_path %>
			<% else %>
				<h4> <%= link_to user.username, user_path(user), class: "header-link" %> </h4>
				<%= link_to image_tag(user.avatar.url(:thumb), :class => "img-circle avatar img-discover center"), user_path(user) %>
			<% end %>
			</div>
			<div class="col-xs-10">
				<div>
					<span> <h4 class="my-header" style="float:left"> <%= link_to post.title, {controller: "posts", action: "show", id: post.id}, :id => "discover-post-header", :class => "search-link" %> <small> <%= post.location %> </small> </h4>
					 <h5 style="float:right" id="fix-this"> <small> posted on <%= post.created_at.strftime("%b %d") %> </small> </h5> </span>
				</div>
				<div class="col-xs-12 post-result-body">
					<%= post.content.html_safe %>
					<div class="fadeout"></div>
				</div>
			</div>
	</div>
</div>

app/views/posts/_post_activity.html.erb
<div class="container-fluid post blog-border">
	<div class="row">
		<div class="col-xs-12" id="activity-show-post">
			<h4 class="my-header"> <%= link_to post.title, post_path(post), class: "post-header" %> <small> <%= post.location %> </small> <span style="float: right"><small><p>posted <%= time_ago_in_words(post.created_at) %> ago</p></small></span></h4>
			<div class="activity-limit">
			<p> <%= link_to post.content.html_safe, post_path(post), class: "post-content limit just-grey-font"%> </p>
			<div class="fadeout"></div>
			</div>
		</div>
		<div class="container-fluid" >
			<% if post.blog.user == current_user %>

			
				<span style="float:right"> 
					<%= link_to post_path(post), method: :delete, remote: true, class: "btn btn-danger btn-sm", id: "post-delete", data:{confirm: "Are you sure you want to delete this post?"} do %>
  						<span class="glyphicon glyphicon-trash activity-size"></span>
					<% end %>

					<%= link_to edit_post_path(post), method: :get do %>
						<span class="glyphicon glyphicon-pencil activity-size"></span>
					<% end %>
				</span>
			<% end %>
				<div id="comment-count"><span style="float:left"> <%= link_to post_path(post), class: "search-link activity-size" do%> <span> <%=post.comments.count %> comments </span> <%end%> </span>  </div>

		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-2" id="sidebar">
			<h2> Edit Post </h2>
			<%= link_to blog_path(@post.blog_id), :class => "btn btn-default", :id => "post-back" do %>
				<span class="glyphicon glyphicon-chevron-left"></span> Back			
			<% end %>
		</div>
		<div class="col-xs-9 col-xs-offset-3">
			<%= simple_form_for @post, html: {class: "form-horizontal"} do |f| %>
				<div class="form-group">
					<%= f.label :title, class: 'control-label' %>
					  <%= f.text_field :title, class: 'form-control'%>
					</div>
				<div class="form-group">
					<%= f.label :content, class: 'control-label'%>
					  <%= f.cktext_area :content, class: 'form-control', :id => 'sometext', :ckeditor => {:uiColor => '#ffffff'} %>
					  <%= f.hidden_field :blog_id, :value => params[:blogID] %>
					</div>
				<div class="form-group">
					<%= f.label :location, class: 'control-label'%>
					  <%= f.text_field :location, class: 'form-control'%>
					</div>
				<div class="form-group">
					  <%= f.submit "Edit Post", :class => "btn btn-primary" %>
					</div>
				<% end %>
				</div>
		</div>
		</div>
</div>

app/views/posts/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-2" id="sidebar">
			<h2> New Post </h2>
			<%= link_to blog_path(@post.blog_id), :class => "btn btn-default", :id => "post-back" do %>
				<span class="glyphicon glyphicon-chevron-left"></span> Back			
			<% end %>
		</div>
		<div class="col-xs-9 col-xs-offset-3">
			<%= simple_form_for @post, url: {action: "create"}, html: {class: "form-horizontal"} do |f| %>
				<div class="form-group">
					<%= f.label :title, class: 'control-label' %>
					  <%= f.text_field :title, class: 'form-control'%>
					</div>
				<div class="form-group">
					<%= f.label :content, class: 'control-label'%>
					  <%= f.cktext_area :content, class: 'form-control', :id => 'sometext', :ckeditor => {:uiColor => '#ffffff'} %>
					  <%= f.hidden_field :blog_id, :value => params[:blogID] %>
					</div>
				<div class="form-group">
					<%= f.label :location, class: 'control-label'%>
					  <%= f.text_field :location, class: 'form-control'%>
					</div>
				<div class="form-group">
					  <%= f.submit "Post", :class => "btn btn-primary" %>
					</div>
				<% end %>
				</div>
		</div>
		</div>
</div>

app/views/posts/show.html.erb
<body class="post-body">
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12">
			<span>
			<h1 class="my-header" id="mypost-header"> <%= @post.location %> <small style="float:right"> 
			<% if @previous_post != nil %>
				<%= link_to post_path(@previous_post), :class => "btn btn-default", :id => "post-nav" do %>
					<span class="glyphicon glyphicon-chevron-left"></span>			
				<% end %>
			<% else %>
					<span class="glyphicon glyphicon-chevron-left" style="color: #ededed" id="post-nav"></span> 
			<% end %>
			<% if @next_post != nil %>
				<%= link_to post_path(@next_post), :class => "btn btn-default", :id => "post-nav" do %>
					<span class="glyphicon glyphicon-chevron-right"></span> 			
				<% end %>
			<% else %>
					<span class="glyphicon glyphicon-chevron-right" style="color: #ededed" id="post-nav"></span> 
			<% end %></small> </h1>
			 </span>
		</div>


		<div class="col-xs-1" id="post-back">
			<%= link_to blog_path(@post.blog_id), :class => "btn btn-default", :id => "post-back" do %>
				<p><span class="glyphicon glyphicon-chevron-left"></span> Back to Blog</p>
			<% end %>
		</div>


		<div class="col-xs-10 col-xs-offset-1 post">
			<div class="post-title">
				<h3> <%= @post.title %> <small> <%=@post.created_at.strftime("%b %d") %> </h3>
			</div>
			<div class="post-content">
				<p> <%= @post.content.html_safe %> </p>
			</div>
			<div class="comment-area">
				<div class="comments">
					<h3> <%= @post.comments.count %> comments </h3>
					<% if @post.comments != nil %>
						<% @comments.reverse_each do |comment| %>
							<%= render "comments/show", :comment => comment, :post => @post %>
						<% end %>
					<% end %>
				</div>
				<%= render "comments/form" %>
			</div>
		</div>
		</div>
</div>
</body>