config/routes.rb
Rails.application.routes.draw do
    
    mount Ckeditor::Engine => '/ckeditor'

    #Set up devise routes for Users
    devise_for :users

    #If user is signed in set specific homepage
    authenticated :user do
		root to: "users#home", :as => "authenticated-root"
	end

    #standard root
	root to: "home#home"

    #index of all the blogs, used for development
    get 'blogs/index_all', to: 'blogs#index_all'


    get 'users/discover', to: 'users#discover'
    get "users/home", to: "users#home"


    resources :users do
        member do
            get :following
        end
    end

    resources :posts do
        resources :comments
    end

    get "search", to: "search#search"


    resources :relationships, only: [:create, :destroy]

    resources :blogs do
        member do
            get :followers
        end
    end
    

end

app/views/layouts/_navigation_links.html.erb
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"> <%= link_to 'BlogMe', root_path, method: :get, :class => 'navbar-brand' %> </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Discover", users_discover_path, method: :get, :class => 'navbar-link' %></li>
        </ul>

        <%= form_tag(search_path, method: :get, :class => "navbar-form navbar-left") do %>
        <div class="form-group">
          <%= text_field :q, params[:q], :class => "form-control", placeholder: "Search..." %>
        </div>
        <% end %>
        

        <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Hello <%=current_user.username%> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#"><%= link_to 'Your Blogs', blogs_path, :class => 'navbar-link' %></a></li>
              <li><a href="#"><%= link_to 'Your Profile', user_path(current_user), :class => 'navbar-link' %> </a></li>
              <li><a href="#"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></a></li>
              <li><a href="#"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></a></li>
    		<% else %>
    			  <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'%> </li>
    		<% end %>
        </ul>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>BlogMe</title>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
<header>
    <%= render 'layouts/navigation_links' %>
</header>
  <%- flash.each do |name, msg| -%>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  <%- end -%>  


<%= yield %>

</body>
</html>

app/views/layouts/home_layout.html.erb
<html>
<head>
  <title>BlogMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%- flash.each do |name, msg| -%>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  <%- end -%>  


<%= yield %>

</body>
</html>